2023-03-20 04:34:30,448 [INFO   ] [APP] autotrader started with arguments={-c}
2023-03-20 04:34:30,448 [INFO   ] [APP] configuration={"Execution":{"Host":"192.168.112.2","Port":12345},"Information":{"Type":"mmap","Name":"/info/info.dat"},"TeamName":"Galactus_22625","Secret":"sQAvas5gfm0wC9kqx6-ncQ"}
2023-03-20 04:34:30,450 [INFO   ] [CONNECTION] fd=7 connection established: peer=192.168.112.2:12345
2023-03-20 04:34:48,726 [WARNING] [TRADER] error with order 0: out-of-order client_order_id in cancel message
2023-03-20 04:34:48,726 [WARNING] [TRADER] error with order 0: out-of-order client_order_id in cancel message
2023-03-20 04:49:48,517 [ERROR  ] [CONNECTION] fd=7 connection lost:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-03-20 04:49:48,517 [INFO   ] [APP] closing event loop
2023-03-20 04:49:48,517 [INFO   ] [RECEIVER] connection lost
