2023-03-20 03:23:17,323 [INFO   ] [APP] autotrader started with arguments={-c}
2023-03-20 03:23:17,323 [INFO   ] [APP] configuration={"Execution":{"Host":"192.168.48.2","Port":12345},"Information":{"Type":"mmap","Name":"/info/info.dat"},"TeamName":"Galactus_22625","Secret":"QqyBLF0B2YFQ260i9poR9g"}
2023-03-20 03:23:17,326 [INFO   ] [CONNECTION] fd=7 connection established: peer=192.168.48.2:12345
2023-03-20 03:23:35,970 [WARNING] [TRADER] error with order 0: out-of-order client_order_id in cancel message
2023-03-20 03:23:35,970 [WARNING] [TRADER] error with order 0: out-of-order client_order_id in cancel message
2023-03-20 03:38:35,739 [ERROR  ] [CONNECTION] fd=7 connection lost:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-03-20 03:38:35,740 [INFO   ] [APP] closing event loop
2023-03-20 03:38:35,740 [INFO   ] [RECEIVER] connection lost
